services:
  - type: web
    name: comparador-precios
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
